# Generated by Django 5.1.4 on 2024-12-31 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_id', models.CharField(max_length=100, unique=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('pong_win', models.PositiveIntegerField(default=0)),
                ('pong_lose', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], default='ONGOING', max_length=10)),
                ('winner_score', models.PositiveIntegerField(blank=True, null=True)),
                ('loser_score', models.PositiveIntegerField(blank=True, null=True)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_lost', to='pong_app.user')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='pong_app.user')),
            ],
        ),
    ]
