# Generated by Django 5.1.4 on 2024-12-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_date',
        ),
    ]
