# Generated by Django 5.1.4 on 2024-12-31 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_app', '0002_remove_user_last_login_remove_user_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
