# Generated by Django 5.1.4 on 2025-01-01 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_app', '0003_user_register_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponggame',
            old_name='loser',
            new_name='loser_id',
        ),
        migrations.RenameField(
            model_name='ponggame',
            old_name='winner',
            new_name='winner_id',
        ),
        migrations.AlterField(
            model_name='ponggame',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
